# Generated by Django 4.1.2 on 2023-02-19 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name='uuid'),
        ),
    ]
