# Generated by Django 4.1.2 on 2023-02-19 23:47
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    user_model = apps.get_model('users', 'User')
    for row in user_model.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
