# Generated by Django 3.2 on 2021-05-03 23:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Pledge Type',
                'verbose_name_plural': 'Pledge Types',
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geolocation', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('measurement_unit', models.CharField(choices=[('m2', 'm2'), ('acres', 'acres'), ('ha', 'Hectares')], default='ha', max_length=6)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pledges.pledgetype')),
            ],
        ),
    ]
