# Generated by Django 4.0.2 on 2022-02-23 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    operations = [
        migrations.CreateModel(
            name='PledgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Pledge Type',
                'verbose_name_plural': 'Pledge Types',
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326)),
                ('area', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('measurement_unit', models.CharField(choices=[('m2', 'm2'), ('acres', 'Acres'), ('ha', 'Hectares')], default='ha', max_length=6)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pledges.pledgetype')),
                ('geom_type', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=4096, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date Submitted')),
                ('visibility', models.IntegerField(choices=[(0, 'None'), (2, 'Restricted'), (4, 'Default')], default=0, verbose_name='Visibility')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
            },
        ),
    ]

    initial = True

    dependencies = [
    ]

