# Generated by Django 3.2 on 2021-05-09 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
