# Generated by Django 3.2 on 2021-05-23 22:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0002_alter_pledge_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
    ]
