# Generated by Django 3.2 on 2021-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0003_alter_pledge_geolocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='geolocation',
            new_name='geom',
        ),
        migrations.AddField(
            model_name='pledge',
            name='geom_type',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
