# Generated by Django 3.2.5 on 2021-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0005_auto_20210529_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Submitted'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'None'), (2, 'Restricted'), (4, 'Default')], default=0, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='postcode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
