# Generated by Django 3.2.5 on 2021-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0006_auto_20210814_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
