# Generated by Django 3.2.5 on 2022-02-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0007_auto_20211016_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='reason',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
