# Generated by Django 4.0.2 on 2022-03-07 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=80, verbose_name='layer name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this layer should be treated as active. Unselect this instead of deleting layers.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=80, verbose_name='map name')),
                ('slug', models.SlugField(blank=True, max_length=80, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this map should be treated as active. Unselect this instead of deleting maps.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=80, verbose_name='organisation name')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this project should be treated as active. Unselect this instead of deleting projects.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Leave blank to inherit the layer name', max_length=80, null=True, verbose_name='layer title')),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaider.layer')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaider.map')),
            ],
            options={
                'unique_together': {('map', 'layer')},
            },
        ),
        migrations.AddField(
            model_name='map',
            name='layers',
            field=models.ManyToManyField(through='mapaider.MapLayer', to='mapaider.Layer'),
        ),
        migrations.AddField(
            model_name='map',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaider.organization'),
        ),
        migrations.AddField(
            model_name='layer',
            name='maps',
            field=models.ManyToManyField(through='mapaider.MapLayer', to='mapaider.Map'),
        ),
        migrations.AddField(
            model_name='layer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaider.organization'),
        ),
    ]
