# Generated by Django 4.0.2 on 2022-03-07 23:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapaider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=80, verbose_name='feature name')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326, verbose_name='geometry')),
                ('geom_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='geometry type')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('data', models.JSONField(blank=True, null=True, verbose_name='feature data')),
                ('visibility', models.IntegerField(choices=[(0, 'None'), (2, 'Restricted'), (4, 'Default')], default=0, verbose_name='visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapaider.layer')),
            ],
            options={
                'verbose_name': 'Map Feature',
                'verbose_name_plural': 'Map Features',
            },
        ),
    ]
