# Generated by Django 4.0.2 on 2022-10-16 19:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapaider', '0002_mapfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'ordering': ['priority'], 'verbose_name': 'Map Layer', 'verbose_name_plural': 'Map Layers'},
        ),
        migrations.RemoveField(
            model_name='layer',
            name='maps',
        ),
        migrations.AddField(
            model_name='layer',
            name='contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='field_set',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='field set'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='mapfeature',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='feature data'),
        ),
        migrations.AlterField(
            model_name='mapfeature',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326, verbose_name='geometry'),
        ),
        migrations.AlterField(
            model_name='mapfeature',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mapaider.layer'),
        ),
        migrations.CreateModel(
            name='MapLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=120, verbose_name='link label')),
                ('url', models.URLField(verbose_name='link url')),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mapaider.map')),
            ],
            options={
                'verbose_name': 'Map Link',
                'verbose_name_plural': 'Map Links',
                'ordering': ['sort'],
            },
        ),
    ]
