# Generated by Django 4.1.2 on 2023-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaider', '0004_membership_organization_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='configuration'),
        ),
    ]
