# Generated by Django 4.2.28 on 2026-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaider', '0005_layer_config'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maplayer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='maplayer',
            constraint=models.UniqueConstraint(fields=('map', 'layer'), name='unique_maplayer_map_layer'),
        ),
    ]
